C:\Users\meteh\anaconda3\Lib\site-packages\google\protobuf\internal\well_known_types.py:174: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.FromDatetime(datetime.datetime.utcnow())
[93mWARNING [0m:   DEPRECATED FEATURE: flwr.client.start_numpy_client() is deprecated.
	Instead, use `flwr.client.start_client()` by ensuring you first call the `.to_client()` method as shown below:
	flwr.client.start_client(
		server_address='<IP>:<PORT>',
		client=FlowerClient().to_client(), # <-- where FlowerClient is of type flwr.client.NumPyClient object
	)
	Using `start_numpy_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

[93mWARNING [0m:   DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

[92mINFO [0m:
[92mINFO [0m:      Received: get_parameters message 3217799b-1198-47d6-bf51-c06bcf366397
[91mERROR [0m:     Client raised an exception.
Traceback (most recent call last):
  File "C:\Users\meteh\anaconda3\Lib\site-packages\flwr\client\app.py", line 571, in start_client_internal
    reply_message = client_app(message=message, context=context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\meteh\anaconda3\Lib\site-packages\flwr\client\client_app.py", line 144, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\meteh\anaconda3\Lib\site-packages\flwr\client\client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\meteh\anaconda3\Lib\site-packages\flwr\client\message_handler\message_handler.py", line 119, in handle_legacy_message_from_msgtype
    get_parameters_res = maybe_call_get_parameters(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\meteh\anaconda3\Lib\site-packages\flwr\client\client.py", line 204, in maybe_call_get_parameters
    return client.get_parameters(get_parameters_ins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\meteh\anaconda3\Lib\site-packages\flwr\client\numpy_client.py", line 215, in _get_parameters
    parameters_proto = ndarrays_to_parameters(parameters)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\meteh\anaconda3\Lib\site-packages\flwr\common\parameter.py", line 28, in ndarrays_to_parameters
    tensors = [ndarray_to_bytes(ndarray) for ndarray in ndarrays]
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\meteh\anaconda3\Lib\site-packages\flwr\common\parameter.py", line 43, in ndarray_to_bytes
    np.save(bytes_io, ndarray, allow_pickle=False)
  File "C:\Users\meteh\anaconda3\Lib\site-packages\numpy\lib\npyio.py", line 546, in save
    format.write_array(fid, arr, allow_pickle=allow_pickle,
  File "C:\Users\meteh\anaconda3\Lib\site-packages\numpy\lib\format.py", line 715, in write_array
    raise ValueError("Object arrays cannot be saved when "
ValueError: Object arrays cannot be saved when allow_pickle=False
Exception in thread Thread-15 (start_federated_client):
Traceback (most recent call last):
  File "C:\Users\meteh\anaconda3\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\meteh\anaconda3\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\meteh\OneDrive\Desktop\federated_learning_hospital_data\app.py", line 266, in start_federated_client
    fl.client.start_numpy_client(server_address="localhost:8080", client=client)
  File "C:\Users\meteh\anaconda3\Lib\site-packages\flwr\client\app.py", line 731, in start_numpy_client
    start_client(
  File "C:\Users\meteh\anaconda3\Lib\site-packages\flwr\client\app.py", line 201, in start_client
    start_client_internal(
  File "C:\Users\meteh\anaconda3\Lib\site-packages\flwr\client\app.py", line 578, in start_client_internal
    raise ex
  File "C:\Users\meteh\anaconda3\Lib\site-packages\flwr\client\app.py", line 571, in start_client_internal
    reply_message = client_app(message=message, context=context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\meteh\anaconda3\Lib\site-packages\flwr\client\client_app.py", line 144, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\meteh\anaconda3\Lib\site-packages\flwr\client\client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\meteh\anaconda3\Lib\site-packages\flwr\client\message_handler\message_handler.py", line 119, in handle_legacy_message_from_msgtype
    get_parameters_res = maybe_call_get_parameters(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\meteh\anaconda3\Lib\site-packages\flwr\client\client.py", line 204, in maybe_call_get_parameters
    return client.get_parameters(get_parameters_ins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\meteh\anaconda3\Lib\site-packages\flwr\client\numpy_client.py", line 215, in _get_parameters
    parameters_proto = ndarrays_to_parameters(parameters)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\meteh\anaconda3\Lib\site-packages\flwr\common\parameter.py", line 28, in ndarrays_to_parameters
    tensors = [ndarray_to_bytes(ndarray) for ndarray in ndarrays]
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\meteh\anaconda3\Lib\site-packages\flwr\common\parameter.py", line 43, in ndarray_to_bytes
    np.save(bytes_io, ndarray, allow_pickle=False)
  File "C:\Users\meteh\anaconda3\Lib\site-packages\numpy\lib\npyio.py", line 546, in save
    format.write_array(fid, arr, allow_pickle=allow_pickle,
  File "C:\Users\meteh\anaconda3\Lib\site-packages\numpy\lib\format.py", line 715, in write_array
    raise ValueError("Object arrays cannot be saved when "
ValueError: Object arrays cannot be saved when allow_pickle=False
